export const TIMELINE_YEAR_TICK_HEIGHT_PERCENTAGE = 8 / 10
export const TIMELINE_YEAR_TICK_WIDTH = 1
export const TIMELINE_YEAR_TICK_FILL = '#000'

export const TIMELINE_MONTH_TICK_HEIGHT_PERCENTAGE = 6 / 10
export const TIMELINE_MONTH_TICK_WIDTH = 1
export const TIMELINE_MONTH_TICK_FILL = '#000'

export const TIMELINE_DAY_TICK_HEIGHT_PERCENTAGE = 5 / 10
export const TIMELINE_DAY_TICK_WIDTH = 1
export const TIMELINE_DAY_TICK_FILL = '#000'

export const TIMELINE_HOUR_TICK_HEIGH_PERCENTAGET = 4 / 10
export const TIMELINE_HOUR_TICK_WIDTH = 1
export const TIMELINE_HOUR_TICK_FILL = '#000'

export const TIMELINE_MINUTE_TICK_HEIGHT_PERCENTAGE = 3 / 10
export const TIMELINE_MINUTE_TICK_WIDTH = 1
export const TIMELINE_MINUTE_TICK_FILL = '#000'

export const TIMELINE_SECOND_TICK_HEIGHT_PERCENTAGE = 2 / 10
export const TIMELINE_SECOND_TICK_WIDTH = 1
export const TIMELINE_SECOND_TICK_FILL = '#000'
